services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001

    volumes:
      - ./PC/mosquittoData/config:/mosquitto/config
      - ./PC/mosquittoData/data:/mosquitto/data
      - ./PC/mosquittoData/log:/mosquitto/log

    
    stdin_open: true
    tty: true
